source = ~/.config/hypr/mocha.conf

general {
    hide_cursor = true
    grace = 0
    no_fade_in = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.02
    contrast = 1.1
    brightness = 0.9
}

label {
    monitor =
    text = $TIME
    font_size = 64
    color = $text
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 60
    position = 0, -40
    dots_center = true
    fade_on_empty = false
    font_color = $text
    inner_color = $base
    outer_color = $blue
    check_color = $yellow
    fail_color = $red
    outline_thickness = 2
    placeholder_text = Password…
}

