# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[os]
disabled = false
style = "bold blue"

[os.symbols]
Arch = " "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
symbol = "📦 "

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = '󰠅 '
style = 'blue bold'

[kubernetes]
format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"

[directory]
read_only = " 🔒"

[docker_context]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[git_status]
disabled=false

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nim]
symbol = "👑 "

[nodejs]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[sudo]
style = "bold green"
symbol = "👩‍💻 "
disabled=false

